server:
  port: ${API_PORT:8990}
  servlet:
    context-path: "/shop_kafka_producer/api"
  # For include message error to http response!!!
  error:
    include-message: always

spring:
  application:
    name: shop_kafka_producer
  kafka:
    bootstrap-servers: 192.168.1.20:9092
    producer:
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      spring:
        json:
          trusted: true
    consumer:
      properties:
        spring.json.trusted.packages: "*"
