server:
  port: ${API_PORT:8990}
  servlet:
    context-path: "/shop_kafka_receiver/api"
  # For include message error to http response!!!
  error:
    include-message: always

spring:
  application:
    name: shop_kafka_receiver

  kafka:
    consumer:
      bootstrap-servers: 192.168.1.20:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


